ManagementSystem.Client.Admin/Models/ErrorViewModel.cs
using System;

namespace ManagementSystem.Client.Admin.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ManagementSystem.Client.Admin/Controllers/HomeController.cs
using ManagementSystem.Client.Admin.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace ManagementSystem.Client.Admin.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ManagementSystem.Client.Admin/Controllers/StandardController.cs
using ManagementSystem.Helpers;
using ManagementSystem.Models.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ManagementSystem.Client.Admin.Controllers
{
    public class StandardController : Controller
    {
        const string BASE_URL = "https://localhost:44375/api/standard";
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult All()
        {
            string url = $"{BASE_URL}";
            IEnumerable<Standard> standards = CallManager<IEnumerable<Standard>>.Get(url);
            if (standards != null)
                return View(standards);
            else
                return BadRequest();
        }

        public ActionResult Details(int id)
        {
            string url = $"{BASE_URL}/{id}";
            Standard standard = CallManager<Standard>.Get(url);
            return View(standard);
        }


        public ActionResult Create()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Standard stn)
        {
            try
            {
                CallManager<Standard>.Post(stn, BASE_URL);
                return RedirectToAction(nameof(All));
            }
            catch
            {
                return View();
            }
        }


        public ActionResult Edit(int id)
        {
            string url = $"{BASE_URL}/{id}";
            Standard standard = CallManager<Standard>.Get(url);
            return View(standard);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Standard stn)
        {
            try
            {
                string url = $"{BASE_URL}/{id}";
                CallManager<Standard>.Put(stn, url);
                return RedirectToAction(nameof(All));
            }
            catch
            {
                return View();
            }
        }


        public ActionResult Delete(int id)
        {
            string url = $"{BASE_URL}/{id}";
            Standard standard = CallManager<Standard>.Get(url);
            return View(standard);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, Standard stn)
        {
            try
            {
                string url = $"{BASE_URL}/{id}";
                CallManager<Standard>.Delete(stn, url);
                return RedirectToAction(nameof(All));
            }
            catch
            {
                return View();
            }
        }
    }
}

ManagementSystem.Client.Admin/Controllers/StudentController.cs
using ManagementSystem.Helpers;
using ManagementSystem.Models;
using ManagementSystem.Models.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ManagementSystem.Client.Admin.Controllers
{
    public class StudentController : Controller
    {
        const string BASE_URL = "https://localhost:44375/api/student";
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult All()
        {
            string url = $"{BASE_URL}";
            IEnumerable<Student> standards = CallManager<IEnumerable<Student>>.Get(url);
            if (standards != null)
                return View(standards);
            else
                return BadRequest();
        }

        public ActionResult Details(int id)
        {
            string url = $"{BASE_URL}/{id}";
            Student standard = CallManager<Student>.Get(url);
            return View(standard);
        }


        public ActionResult Create()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Student stn)
        {
            try
            {
                CallManager<Student>.Post(stn, BASE_URL);
                return RedirectToAction(nameof(All));
            }
            catch
            {
                return View();
            }
        }


        public ActionResult Edit(int id)
        {
            string url = $"{BASE_URL}/{id}";
            Student standard = CallManager<Student>.Get(url);
            return View(standard);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Student stn)
        {
            try
            {
                string url = $"{BASE_URL}/{id}";
                CallManager<Student>.Put(stn, url);
                return RedirectToAction(nameof(All));
            }
            catch
            {
                return View();
            }
        }


        public ActionResult Delete(int id)
        {
            string url = $"{BASE_URL}/{id}";
            Student standard = CallManager<Student>.Get(url);
            return View(standard);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, Student stn)
        {
            try
            {
                string url = $"{BASE_URL}/{id}";
                CallManager<Student>.Delete(stn, url);
                return RedirectToAction(nameof(All));
            }
            catch
            {
                return View();
            }
        }
    }
}

ManagementSystem.Client.Admin/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome Admin</h1>
</div>

ManagementSystem.Client.Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ManagementSystem Admin</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ManagementSystem Admin</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="Index">Manage Students</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Standard" asp-action="Index">Manage Standards</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - ManagementSystem.Client.Admin - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ManagementSystem.Client.Admin/Views/Standard/All.cshtml
@model IEnumerable<ManagementSystem.Models.Models.Standard>

@{
    ViewData["Title"] = "All";
}

<h1>All</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.StandardID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.StandardName)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.StandardID)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.StandardName)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.StandardID }) |
                    @Html.ActionLink("Details", "Details", new { id = item.StandardID }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.StandardID })
                </td>
            </tr>
        }
    </tbody>
</table>

ManagementSystem.Client.Admin/Views/Standard/Create.cshtml
@model ManagementSystem.Models.Models.Standard

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Standard</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="StandardName" class="control-label"></label>
                <input asp-for="StandardName" class="form-control" />
                <span asp-validation-for="StandardName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

ManagementSystem.Client.Admin/Views/Standard/Delete.cshtml
@model ManagementSystem.Models.Models.Standard

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Standard</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StandardID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StandardID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StandardName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StandardName)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

ManagementSystem.Client.Admin/Views/Standard/Details.cshtml
@model ManagementSystem.Models.Models.Standard

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Standard</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.StandardID)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.StandardID)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.StandardName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.StandardName)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { id = Model.StandardID }) |
    <a asp-action="Index">Back to List</a>
</div>

ManagementSystem.Client.Admin/Views/Standard/Edit.cshtml
@model ManagementSystem.Models.Models.Standard

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Standard</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="StandardID" class="control-label"></label>
                <input asp-for="StandardID" class="form-control" />
                <span asp-validation-for="StandardID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StandardName" class="control-label"></label>
                <input asp-for="StandardName" class="form-control" />
                <span asp-validation-for="StandardName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

ManagementSystem.Client.Admin/Views/Standard/Index.cshtml
@{
    ViewData["Title"] = "Index";
}


<a asp-area="" asp-controller="Standard" asp-action="All">Get All Standards</a>
<br />
<a asp-area="" asp-controller="Standard" asp-action="Create">Add New Standard</a>

ManagementSystem.Client.Admin/Views/Student/All.cshtml
@model IEnumerable<ManagementSystem.Models.Models.Student>

@{
    ViewData["Title"] = "All";
}

<h1>View</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.StudentID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Age)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Address)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Phone)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.StandardID)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.StudentID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Age)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Phone)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StandardID)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>

ManagementSystem.Client.Admin/Views/Student/Create.cshtml
@model ManagementSystem.Models.Models.Student

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Student</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="StudentID" class="control-label"></label>
                <input asp-for="StudentID" class="form-control" />
                <span asp-validation-for="StudentID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Age" class="control-label"></label>
                <input asp-for="Age" class="form-control" />
                <span asp-validation-for="Age" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label"></label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StandardID" class="control-label"></label>
                <input asp-for="StandardID" class="form-control" />
                <span asp-validation-for="StandardID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="All">Back to List</a>
</div>

ManagementSystem.Client.Admin/Views/Student/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<a asp-area="" asp-controller="Student" asp-action="All">Get All Students</a>
<br/>
<a asp-area="" asp-controller="Student" asp-action="Create">Add New Student</a>